"""Seed the people table with a curated list of famous people + Wikipedia images.

Usage: uv run python scripts/seed_people_static.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db import supabase

# Curated list: name, aliases, category, Wikimedia Commons image filename
PEOPLE = [
    ("Dwayne Johnson", ["The Rock"], "actor", "Dwayne_Johnson_2014_(cropped).jpg"),
    ("Leonardo DiCaprio", ["Leo"], "actor", "Leonardo_DiCaprio_2019_by_Glenn_Francis.jpg"),
    ("Beyoncé", ["Queen Bey"], "musician", "Beyonc%C3%A9_-_Wikimedia_2.jpg"),
    ("Taylor Swift", [], "musician", "Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_(1).png"),
    ("Cristiano Ronaldo", ["CR7"], "athlete", "Cristiano_Ronaldo_WC2022_-_01.jpg"),
    ("Lionel Messi", ["Leo Messi"], "athlete", "Lionel-Messi-Argentina-2022-FIFA-World-Cup_(cropped).jpg"),
    ("Tom Hanks", [], "actor", "Tom_Hanks_TIFF_2019.jpg"),
    ("Oprah Winfrey", [], "other", "Oprah_Winfrey_2010.jpg"),
    ("Elon Musk", [], "other", "Elon_Musk_Royal_Society_(crop2).jpg"),
    ("Adele", [], "musician", "Adele_for_Vogue_in_2021.png"),
    ("Brad Pitt", [], "actor", "Brad_Pitt_2019_by_Glenn_Francis.jpg"),
    ("Angelina Jolie", [], "actor", "Angelina_Jolie_2_June_2014_(cropped).jpg"),
    ("Morgan Freeman", [], "actor", "Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_(cropped).jpg"),
    ("Will Smith", ["The Fresh Prince"], "actor", "TechCrunch_Disrupt_2019_(48834434641)_(cropped).jpg"),
    ("Jennifer Lawrence", ["JLaw"], "actor", "Jennifer_Lawrence_SDCC_2015_X-Men.jpg"),
    ("Robert Downey Jr.", ["RDJ"], "actor", "Robert_Downey_Jr_2014_Comic_Con_(cropped).jpg"),
    ("Scarlett Johansson", [], "actor", "Scarlett_Johansson_by_Gage_Skidmore_2_(cropped).jpg"),
    ("Tom Cruise", [], "actor", "Tom_Cruise_by_Gage_Skidmore_3.jpg"),
    ("Meryl Streep", [], "actor", "Meryl_Streep_December_2018.jpg"),
    ("Denzel Washington", [], "actor", "Denzel_Washington_2018.jpg"),
    ("Rihanna", ["RiRi"], "musician", "Rihanna_Fenty_2018.png"),
    ("Drake", ["Drizzy"], "musician", "Drake_July_2016_(cropped).jpg"),
    ("Ed Sheeran", [], "musician", "Ed_Sheeran-6886_(cropped).jpg"),
    ("Bruno Mars", [], "musician", "Bruno_Mars,_Las_Vegas_2023.jpg"),
    ("Lady Gaga", ["Stefani Germanotta"], "musician", "Lady_Gaga_at_Joe_Biden%27s_inauguration_(cropped_2).jpg"),
    ("Justin Bieber", [], "musician", "Justin_Bieber_in_2015.jpg"),
    ("Eminem", ["Slim Shady", "Marshall Mathers"], "musician", "Eminem_-_Concert_for_Valor_in_Washington,_D.C._Nov._11,_2014_(2)_(Cropped).jpg"),
    ("Kanye West", ["Ye"], "musician", "Kanye_West_at_the_2009_Tribeca_Film_Festival_(crop_2).jpg"),
    ("LeBron James", ["King James"], "athlete", "LeBron_James_-_51959723161_(cropped).jpg"),
    ("Serena Williams", [], "athlete", "Serena_Williams_at_2013_US_Open.jpg"),
    ("Usain Bolt", [], "athlete", "Usain_Bolt_Olympics_celebration.jpg"),
    ("Roger Federer", [], "athlete", "Roger_Federer_(26_June_2009,_Wimbledon)_2_(crop).jpg"),
    ("Michael Jordan", ["MJ"], "athlete", "Michael_Jordan_in_2014.jpg"),
    ("Neymar", ["Neymar Jr"], "athlete", "Neymar_Jr_2022_FIFA_World_Cup_(cropped).jpg"),
    ("Stephen Curry", ["Steph Curry"], "athlete", "Stephen_Curry_dribbling_2016_(cropped).jpg"),
    ("Tiger Woods", [], "athlete", "Tiger_Woods_in_May_2019.jpg"),
    ("Barack Obama", [], "politician", "President_Barack_Obama.jpg"),
    ("Donald Trump", [], "politician", "Donald_Trump_official_portrait.jpg"),
    ("Keanu Reeves", [], "actor", "Keanu_Reeves_(crop_and_levels)_(cropped).jpg"),
    ("Chris Hemsworth", [], "actor", "Chris_Hemsworth_by_Gage_Skidmore_2_(cropped).jpg"),
    ("Gal Gadot", [], "actor", "Gal_Gadot_(2018).jpg"),
    ("Ryan Reynolds", [], "actor", "Ryan_Reynolds_by_Gage_Skidmore.jpg"),
    ("Margot Robbie", [], "actor", "Margot_Robbie_(28558206237)_(cropped).jpg"),
    ("Chris Evans", [], "actor", "Chris_Evans_SDCC_2019.jpg"),
    ("Zendaya", [], "actor", "Zendaya_-_2019_by_Glenn_Francis.jpg"),
    ("Billie Eilish", [], "musician", "Billie_Eilish_2019_by_Glenn_Francis_(cropped)_2.jpg"),
    ("Post Malone", ["Austin Post"], "musician", "Post_Malone_Stavernfestivalen_2018_(202940).jpg"),
    ("Ariana Grande", [], "musician", "Ariana_Grande_Sweetener_World_Tour7_(cropped).jpg"),
    ("Selena Gomez", [], "musician", "Selena_Gomez_-_Cannes_2019_(3)_(cropped).jpg"),
    ("Katy Perry", [], "musician", "Katy_Perry_at_the_Biden_inauguration.jpg"),
    ("Travis Scott", ["La Flame"], "musician", "Travis_Scott_-_Openair_Frauenfeld_2019_08.jpg"),
    ("The Weeknd", ["Abel Tesfaye"], "musician", "The_Weeknd_Portrait_by_Brian_Ziff.jpg"),
    ("Dua Lipa", [], "musician", "Dua_Lipa_%28cropped%29.jpg"),
    ("Cardi B", [], "musician", "Cardi_B_at_Made_in_America_2019.jpg"),
    ("Jeff Bezos", [], "other", "Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_(39074799225)_(cropped).jpg"),
    ("Mark Zuckerberg", ["Zuck"], "other", "Mark_Zuckerberg_F8_2019_Keynote_(32830578717)_(cropped).jpg"),
    ("Bill Gates", [], "other", "Bill_Gates_2017_(cropped).jpg"),
    ("Albert Einstein", [], "other", "Einstein_1921_by_F_Schmutzer_-_restoration.jpg"),
    ("Marilyn Monroe", [], "actor", "Marilynmonroealivestill.jpg"),
    ("Muhammad Ali", ["Cassius Clay"], "athlete", "Muhammad_Ali_NYWTS.jpg"),
    ("Michael Jackson", ["MJ", "King of Pop"], "musician", "Michael_Jackson_in_1988.jpg"),
    ("Elvis Presley", ["The King"], "musician", "Elvis_Presley_promoting_Jailhouse_Rock.jpg"),
    ("Madonna", ["Queen of Pop"], "musician", "Madonna_Rebel_Heart_Tour_2015_-_Stockholm_(23051472299)_(cropped_2).jpg"),
    ("David Bowie", ["Ziggy Stardust"], "musician", "David-Bowie_Chicago_2002-08-08_photoby_Adam-Bielawski-cropped.jpg"),
    ("Freddie Mercury", [], "musician", "Freddie_Mercury_performing_in_New_Haven,_CT,_November_1977.jpg"),
    ("Prince", ["The Artist"], "musician", "Prince_at_Coachella_001.jpg"),
    ("Shakira", [], "musician", "Shakira_2014.jpg"),
    ("Jennifer Lopez", ["JLo"], "musician", "Jennifer_Lopez_at_GLAAD_Media_Awards_(cropped).jpg"),
    ("Tom Brady", ["TB12"], "athlete", "Tom_Brady_2017.jpg"),
    ("Kobe Bryant", ["Black Mamba"], "athlete", "Kobe_Bryant_2014.jpg"),
    ("David Beckham", ["Becks"], "athlete", "David_Beckham_Nov_11_2007.jpg"),
    ("Lewis Hamilton", [], "athlete", "Lewis_Hamilton_2016_Malaysia_2.jpg"),
    ("Rafael Nadal", ["Rafa"], "athlete", "Rafa_Nadal_during_2024_Roland_Garros.jpg"),
    ("Novak Djokovic", ["Nole"], "athlete", "Novak_Djokovic_Trophy_Wimbledon_2019-croped_and_edited.jpg"),
    ("Mike Tyson", ["Iron Mike"], "athlete", "Mike_Tyson_2019_by_Glenn_Francis.jpg"),
    ("Arnold Schwarzenegger", ["The Terminator"], "actor", "Arnold_Schwarzenegger_by_Gage_Skidmore_4.jpg"),
    ("Sylvester Stallone", ["Sly"], "actor", "Sylvester_Stallone_(29256469914)_(cropped).jpg"),
    ("Harrison Ford", [], "actor", "Harrison_Ford_by_Gage_Skidmore_3.jpg"),
    ("Samuel L. Jackson", [], "actor", "Samuel_L._Jackson_2019_by_Glenn_Francis.jpg"),
    ("Al Pacino", [], "actor", "Al_Pacino_(cropped).jpg"),
    ("Robert De Niro", [], "actor", "Robert_De_Niro_canridge.jpg"),
    ("Johnny Depp", [], "actor", "Johnny_Depp_2020.jpg"),
    ("Nicole Kidman", [], "actor", "Nicole_Kidman_Cannes_2017_3.jpg"),
    ("Sandra Bullock", [], "actor", "Sandra_Bullock_(9192365016)_(cropped).jpg"),
    ("Julia Roberts", [], "actor", "Julia_Roberts_2011_Shankbone_3.JPG"),
    ("Anne Hathaway", [], "actor", "Anne_Hathaway_for_Vogue_UK_05.png"),
    ("Natalie Portman", [], "actor", "Natalie_Portman_Cannes_2015_5_(cropped).jpg"),
    ("Emma Watson", [], "actor", "Emma_Watson_2013.jpg"),
    ("Emma Stone", [], "actor", "Emma_Stone_at_the_39th_Mill_Valley_Film_Festival_(cropped).jpg"),
    ("Chris Pratt", [], "actor", "Chris_Pratt_2018.jpg"),
    ("Jason Momoa", [], "actor", "Jason_Momoa_(43055621224)_(cropped).jpg"),
    ("Vin Diesel", [], "actor", "Vin_Diesel_2013_SDCC.jpg"),
    ("Demi Lovato", [], "musician", "Demi_Lovato_2020.png"),
    ("Miley Cyrus", [], "musician", "Miley_Cyrus_Glastonbury_2019_(cropped).jpg"),
    ("Shawn Mendes", [], "musician", "Shawn_Mendes_at_The_Global_Awards_2019.jpg"),
    ("Harry Styles", [], "musician", "Harry_Styles_November_2014.jpg"),
    ("Nicki Minaj", [], "musician", "Nicki_Minaj_2019.jpg"),
    ("Jay-Z", ["Shawn Carter", "Hov"], "musician", "Jay-Z_%40_Shawn_Carter_Foundation_2011_Cropped.jpg"),
    ("Snoop Dogg", ["Snoop Lion"], "musician", "Snoop_Dogg_2019_by_Glenn_Francis.jpg"),
    ("Kendrick Lamar", ["K-Dot"], "musician", "Kendrick_Lamar_2016.jpg"),
    ("Bob Marley", [], "musician", "Bob-Marley_3.jpg"),
    ("John Lennon", [], "musician", "John_Lennon_1969_(cropped).jpg"),
    ("Paul McCartney", ["Macca"], "musician", "Paul_McCartney_in_October_2018.jpg"),
    ("Elton John", [], "musician", "Elton_John_2023_HQ.jpg"),
    ("Stevie Wonder", [], "musician", "Stevie_Wonder_2018.jpg"),
    ("Pelé", ["Edson Arantes"], "athlete", "Pele_con_brasil_(cropped).jpg"),
    ("Diego Maradona", [], "athlete", "Maradona-Mundial_86_con_la_copa.JPG"),
    ("Wayne Gretzky", ["The Great One"], "athlete", "Wayne_Gretzky_1997.jpg"),
    ("Simone Biles", [], "athlete", "Simone_Biles_in_2024_(cropped).jpg"),
    ("Naomi Osaka", [], "athlete", "Naomi_Osaka_(2019).jpg"),
    ("Conor McGregor", ["The Notorious"], "athlete", "Conor_McGregor_2018_(cropped).jpg"),
    ("Floyd Mayweather", ["Money"], "athlete", "Floyd_Mayweather,_Jr._2011.jpg"),
    ("Megan Thee Stallion", ["Hot Girl Meg"], "musician", "Megan_Thee_Stallion_2019.jpg"),
    ("SZA", ["Solána Rowe"], "musician", "SZA_2022.jpg"),
    ("Bad Bunny", ["Benito"], "musician", "Bad_Bunny_2023.jpg"),
    ("Timothée Chalamet", [], "actor", "Timoth%C3%A9e_Chalamet_by_Gage_Skidmore_2.jpg"),
    ("Florence Pugh", [], "actor", "Florence_Pugh_(48462887397)_(cropped).jpg"),
    ("Pedro Pascal", [], "actor", "Pedro_Pascal_by_Gage_Skidmore.jpg"),
    ("Cillian Murphy", [], "actor", "Cillian_Murphy_Press_Conference_The_Party_Berlinale_2017_02_(cropped).jpg"),
    ("Austin Butler", [], "actor", "Austin_Butler_Berlinale_2022_(cropped).jpg"),
    ("Sydney Sweeney", [], "actor", "Sydney_Sweeney_2024.jpg"),
    ("Jenna Ortega", [], "actor", "Jenna_Ortega_by_Gage_Skidmore.jpg"),
    ("Ana de Armas", [], "actor", "Ana_de_Armas_by_Gage_Skidmore.jpg"),
    ("Oscar Isaac", [], "actor", "Oscar_Isaac_by_Gage_Skidmore.jpg"),
    ("Jeff Goldblum", [], "actor", "Jeff_Goldblum_by_Gage_Skidmore_3.jpg"),
    ("Danny DeVito", [], "actor", "Danny_DeVito_by_Gage_Skidmore.jpg"),
    ("Jackie Chan", [], "actor", "Jackie_Chan_July_2016.jpg"),
    ("Jim Carrey", [], "actor", "Jim_Carrey_2008.jpg"),
    ("Adam Sandler", [], "actor", "Adam_Sandler_Cannes_2017.jpg"),
    ("Kevin Hart", [], "actor", "Kevin_Hart_2014_(cropped_2).jpg"),
    ("Doja Cat", [], "musician", "Doja_Cat_2021_Met_Gala_(cropped).jpg"),
    ("Lana Del Rey", ["Elizabeth Grant"], "musician", "Lana_Del_Rey_%40_Grammy_Museum_10_13_2019_(49311023203).jpg"),
    ("Tyler, the Creator", [], "musician", "Tyler%2C_the_Creator_2019_Muhammaddo.jpg"),
    ("J. Cole", ["Jermaine Cole"], "musician", "J._Cole_2023.jpg"),
    ("21 Savage", [], "musician", "21_Savage_2018.jpg"),
    ("Lizzo", [], "musician", "Lizzo_2023.jpg"),
    ("Olivia Rodrigo", [], "musician", "Olivia_Rodrigo_at_the_66th_Annual_Grammy_Awards.png"),
    ("Ice Spice", [], "musician", "Ice_Spice_BET_Awards_2023_2_(cropped).jpg"),
    ("Travis Kelce", [], "athlete", "Travis_Kelce_2023.jpg"),
    ("Patrick Mahomes", [], "athlete", "Patrick_Mahomes_2023.jpg"),
    ("Shohei Ohtani", [], "athlete", "Shohei_Ohtani.jpg"),
    ("Giannis Antetokounmpo", ["Greek Freak"], "athlete", "Giannis_Antetokounmpo_(51682858772)_(cropped).jpg"),
    ("Luka Dončić", ["Luka Doncic"], "athlete", "Luka_Doncic_(51680504806)_(cropped).jpg"),
    ("Kylian Mbappé", ["Kylian Mbappe"], "athlete", "Kylian_Mbapp%C3%A9_201802.jpg"),
    ("Erling Haaland", [], "athlete", "Erling_Haaland_2023.jpg"),
    ("Max Verstappen", [], "athlete", "Max_Verstappen_2017_Malaysia_3.jpg"),
    ("Naomi Campbell", [], "other", "Naomi_Campbell_Cannes_2018_2_(cropped).jpg"),
    ("Kim Kardashian", [], "other", "Kim_Kardashian_2019.jpg"),
    ("Kylie Jenner", [], "other", "Kylie_Jenner_at_2023_Vanity_Fair_Oscar_Party.jpg"),
    ("Gordon Ramsay", [], "other", "Gordon_Ramsay.jpg"),
    ("David Attenborough", ["Sir David"], "other", "David_Attenborough_(crop).jpg"),
    ("Stephen Hawking", [], "other", "Stephen_Hawking.StarChild.jpg"),
    ("Nelson Mandela", ["Madiba"], "politician", "Nelson_Mandela-2008_(edit).jpg"),
    ("Queen Elizabeth II", [], "politician", "Queen_Elizabeth_II_in_March_2015.jpg"),
    ("Pope Francis", [], "other", "Pope_Francis_in_March_2013.jpg"),
    ("Malala Yousafzai", [], "other", "Shinzo_Abe_and_Malala_Yousafzai_(1)_(cropped).jpg"),
    ("Greta Thunberg", [], "other", "Greta_Thunberg_urges_MEPs_to_show_climate_leadership_(49618310531)_(cropped).jpg"),
    ("Marie Curie", [], "other", "Marie_Curie_c._1920s.jpg"),
    ("Frida Kahlo", [], "other", "Frida_Kahlo,_by_Guillermo_Kahlo.jpg"),
    ("Audrey Hepburn", [], "actor", "Audrey_Hepburn_1956.jpg"),
    ("Charlie Chaplin", ["The Tramp"], "actor", "Charlie_Chaplin.jpg"),
    ("Bruce Lee", [], "actor", "Bruce_Lee_1973.jpg"),
    ("Clint Eastwood", [], "actor", "Clint_Eastwood_at_2010_New_York_Film_Festival.jpg"),
    ("Jack Nicholson", [], "actor", "Jack_Nicholson_2002.jpg"),
    ("Robin Williams", [], "actor", "Robin_Williams_2011a_(2).jpg"),
    ("Eddie Murphy", [], "actor", "Eddie_Murphy_by_David_Shankbone.jpg"),
    ("Sean Connery", [], "actor", "Sean_Connery_1999.jpg"),
    ("Cate Blanchett", [], "actor", "Cate_Blanchett_Cannes_2018_2_(cropped).jpg"),
    ("Viola Davis", [], "actor", "Viola_Davis_by_Gage_Skidmore.jpg"),
    ("Joaquin Phoenix", [], "actor", "Joaquin_Phoenix_at_the_2018_Berlin_Film_Festival.jpg"),
    ("Matt Damon", [], "actor", "Matt_Damon_TIFF_2019.jpg"),
    ("George Clooney", [], "actor", "George_Clooney_2016.jpg"),
    ("Benedict Cumberbatch", [], "actor", "Benedict_Cumberbatch_SDCC_2014.jpg"),
    ("Hugh Jackman", [], "actor", "Hugh_Jackman_by_Gage_Skidmore.jpg"),
    ("Jake Gyllenhaal", [], "actor", "Jake_Gyllenhaal_2019_by_Glenn_Francis.jpg"),
    ("Idris Elba", [], "actor", "Idris_Elba-4580_(cropped).jpg"),
    ("Lupita Nyong'o", [], "actor", "Lupita_Nyong%27o_%2866885343_%E2%80%93_cropped_3x4%29.jpg"),
    ("Amy Adams", [], "actor", "Amy_Adams_UK_Nocturnal_Animals_Premiere_(cropped).jpg"),
    ("Rachel McAdams", [], "actor", "Rachel_McAdams_Cannes_2018.jpg"),
    ("Charlize Theron", [], "actor", "Charlize-theron-IMG_6045.jpg"),
    ("Kate Winslet", [], "actor", "Kate_Winslet_at_the_2017_Toronto_International_Film_Festival.jpg"),
    ("Millie Bobby Brown", [], "actor", "Millie_Bobby_Brown_by_Gage_Skidmore.jpg"),
    ("Florence Welch", [], "musician", "Florence_Welch_Lollapalooza.jpg"),
    ("Sam Smith", [], "musician", "Sam_Smith_Lollapalooza_2015.jpg"),
    ("Lil Wayne", ["Weezy"], "musician", "Lil_Wayne_2018.jpg"),
    ("50 Cent", ["Curtis Jackson"], "musician", "50_Cent_2023.jpg"),
    ("Pharrell Williams", [], "musician", "Pharrell_Williams_2014.jpg"),
    ("John Legend", [], "musician", "John_Legend_2019_by_Glenn_Francis.jpg"),
    ("Alicia Keys", [], "musician", "Alicia_Keys_-_Agganis_Arena_(cropped).jpg"),
    ("Sia", [], "musician", "Sia_Furler.jpg"),
    ("The Rock", ["Dwayne Johnson"], "actor", "Dwayne_Johnson_Hercules_2014_(cropped).jpg"),
    ("Zlatan Ibrahimović", ["Zlatan Ibrahimovic", "Ibra"], "athlete", "Zlatan_Ibrahimovi%C4%87.jpg"),
    ("Maria Sharapova", [], "athlete", "Maria_Sharapova_(9760174871).jpg"),
    ("Lindsey Vonn", [], "athlete", "Lindsey_Vonn_2018.jpg"),
    ("Michael Phelps", [], "athlete", "Michael_Phelps_Rio_Olympics_2016.jpg"),
    ("Manny Pacquiao", ["Pacman"], "athlete", "Manny_Pacquiao_2019.jpg"),
    ("Venus Williams", [], "athlete", "Venus_Williams_Wimbledon_2017.jpg"),
    ("Kevin Durant", ["KD"], "athlete", "Kevin_Durant_(51928273720)_(cropped).jpg"),
    ("Russell Westbrook", ["Russ"], "athlete", "Russell_Westbrook_2023.jpg"),
    ("James Harden", ["The Beard"], "athlete", "James_Harden_2018_(cropped).jpg"),
    ("Damian Lillard", ["Dame"], "athlete", "Damian_Lillard_2023.jpg"),
    ("Joel Embiid", [], "athlete", "Joel_Embiid_2018.jpg"),
    ("Nikola Jokić", ["Nikola Jokic", "The Joker"], "athlete", "Nikola_Joki%C4%87.jpg"),
    ("Mohamed Salah", ["Mo Salah"], "athlete", "Mohamed_Salah_2018.jpg"),
    ("Robert Lewandowski", ["Lewy"], "athlete", "Robert_Lewandowski.jpg"),
    ("Virat Kohli", [], "athlete", "Virat_Kohli.jpg"),
    ("Sachin Tendulkar", [], "athlete", "Sachin_Tendulkar_at_MRF_Pace_Foundation.jpg"),
    ("AB de Villiers", ["Mr. 360"], "athlete", "AB_de_Villiers.jpg"),
]

WIKIMEDIA_BASE = "https://upload.wikimedia.org/wikipedia/commons/thumb"

def image_url(filename: str) -> str:
    """Construct a Wikimedia Commons thumbnail URL (400px wide)."""
    # Wikimedia thumb URLs follow: /thumb/{hash1}/{hash2}/{filename}/400px-{filename}
    # We use the direct File: URL instead which always works
    return f"https://commons.wikimedia.org/wiki/Special:FilePath/{filename}?width=400"

def main():
    people = []
    seen = set()
    for name, aliases, category, filename in PEOPLE:
        if name in seen:
            continue
        seen.add(name)
        people.append({
            "name": name,
            "aliases": aliases,
            "image_url": image_url(filename),
            "category": category,
            "license": "CC-BY-SA",
            "attribution_url": f"https://commons.wikimedia.org/wiki/File:{filename}",
        })

    print(f"Seeding {len(people)} people...")

    for i in range(0, len(people), 50):
        batch = people[i:i+50]
        supabase.table("people").upsert(batch, on_conflict="name").execute()
        print(f"  Inserted batch {i//50 + 1} ({len(batch)} people)")

    print("Done!")

if __name__ == "__main__":
    main()
